spring:
  application:
    name: SucculentMan-host
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    favicon:
      enabled: false
  aop:
    proxy-target-class: true
  freemarker:
    template-loader-path: ["classpath:/templates/", "classpath:/castemplates/"]

app:
  manager:
#   host: http://www.tangdoudou.club/manager
   host: http://localhost:8080/manager

server:
  context-path: /
  port: 8089
  compression:
    enabled: true
  use-forward-headers: true

#swagger API
springfox:
  documentation:
    swagger:
      v2:
        path: /api/v2/api-docs