spring:
  application:
    name: jinyinwu-wechat
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    favicon:
      enabled: false
  freemarker:
    template-loader-path: ["classpath:/templates/", "classpath:/castemplates/"]

app:
  manager:
   host: http://www.tangdoudou.club/manager

server:
  context-path: /
  port: 8089
  compression:
    enabled: true

#swagger API
springfox:
  documentation:
    swagger:
      path: /api/api-docs